In [1]:
# Starting my first tensorflow code

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.13.0'

In [4]:
# Load a dataset
mnist = tf.keras.datasets.mnist

In [5]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 3s 0us/step


In [6]:
x_train, x_test = x_train/255.0 , x_test/255.0

In [8]:
# Building a machine learning model
# build a tf.keras.Sequential model

In [9]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [10]:
# Sequential is useful for stacking layers where each layer has one inemput tensor and one output tensor. Layers are functions with a known
# mathematical structure that can be reused and have trainable variables. Most tensorflow models are composed of layers.
# This model uses flatten, dense and dropout layers
# for each example the model returns a vector or log-odds scores one for each class

In [11]:
predictions = model(x_train[:1]).numpy()

In [12]:
predictions

array([[-1.1278734 , -0.6520732 ,  0.17808999, -0.00326687,  0.4799379 ,
        -0.1866855 ,  0.28759477, -0.19383205, -0.1964539 , -0.44212732]],
      dtype=float32)

In [13]:
# The tf.nn.softmax function converts these logits  to probabilities for each class

In [16]:
tf.nn.softmax(predictions).numpy()

array([[0.03556062, 0.05722775, 0.1312629 , 0.10949132, 0.1775141 ,
        0.09114272, 0.14645335, 0.09049369, 0.09025674, 0.0705968 ]],
      dtype=float32)

In [17]:
# Define a loss function for training using losses.SparseCategoricalCrossEntropy 

In [18]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [19]:
loss_fn

In [20]:
# The loss function takes a vector of ground truth values and a vector of logits and returns a scalar loss for each example.
# This loss is equal to the negative log probability of the true class.
# The loss is zero if the model is sure of the correct class
# This untrained model gives probabilities close to random 1/10 for each class
# So the initial loss should be close to tf.math.log(1/10)

In [21]:
loss_fn(y_train[:1], predictions).numpy()

2.3953285

In [22]:
# Before you start training, configure and compile the model using Keras Model.compile.
# Set the optimizer class adam, set the to the loss_fn, function you defined earlier and specify a metric
# to be evaluated for the model by setting the metrics parameter to accuracy

In [23]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [24]:
# Train and evaluate your model
# Use the model.fit method to adjust your model parameters and minimize the loss

In [25]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2987 - accuracy: 0.9126
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1466 - accuracy: 0.9558
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1096 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0891 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0755 - accuracy: 0.9760


In [26]:
# The model.evaluate method checks the model's performance usually on a validation set or test set

In [27]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0785 - accuracy: 0.9755 - 493ms/epoch - 2ms/step


[0.07845757156610489, 0.9754999876022339]

In [28]:
# The image classifier is trained to 98% accuracy on this dataset
# If you want model to return a probability, you can wrap the  trained model and attach the softmax to it

In [29]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [30]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.0553692e-07, 1.1847511e-08, 1.0797685e-05, 2.7754015e-05,
        4.3720978e-11, 1.9019252e-07, 1.8248807e-12, 9.9995828e-01,
        2.3932282e-07, 2.6280920e-06],
       [5.3229602e-08, 2.1284566e-06, 9.9998319e-01, 1.4400436e-05,
        5.3324320e-15, 4.1386681e-08, 4.8764472e-09, 6.4707083e-14,
        2.3046968e-07, 3.4496838e-13],
       [1.3286004e-07, 9.9916530e-01, 2.9146706e-04, 1.2525690e-05,
        1.1844369e-05, 5.2380199e-07, 6.7722726e-07, 1.9957889e-04,
        3.1783551e-04, 1.9583878e-07],
       [9.9975818e-01, 1.3068918e-10, 2.4770764e-06, 1.1363438e-07,
        2.0447946e-07, 1.9418094e-06, 2.3353103e-04, 1.2543459e-06,
        4.8870254e-07, 1.7619291e-06],
       [3.5425102e-05, 1.0845858e-08, 4.5847660e-06, 1.1287906e-06,
        9.9566334e-01, 5.9309386e-06, 6.2212246e-05, 2.1509998e-04,
        4.0930636e-06, 4.0081572e-03]], dtype=float32)>

In [31]:
# Congratulations, your model is trained